[config]
schemaVersion = "0.0.1"

[package]
namespace = "TheHowlingYonder"
name = "TheHowlingYonderModpack"
versionNumber = "1.12.0"
description = "A modpack for 'The Howling Yonder' server"
websiteUrl = "https://github.com/MLNW/the-howling-yonder-modpack"
containsNsfwContent = false

[package.dependencies]
Atopy-QuickPing = "1.5.3"
Azumatt-AAA_Crafting = "1.0.5"
Azumatt-AzuClock = "1.0.0"
Azumatt-Where_You_At = "1.0.7"
ComfyMods-ComfyQuickSlots = "1.0.9"
denikson-BepInExPack_Valheim = "5.4.1901"
Digitalroot-Digitalroots_Slope_Combat_Assistance = "2.0.2"
Goldenrevolver-Quick_Stack_Store_Sort_Trash_Restock = "1.2.3"
LVH-IT-UseEquipmentInWater = "0.2.3"
makail-ItemDrawers = "0.5.0"
MathiasDecrock-Snap_Points_Made_Easy = "1.3.2"
OdinPlus-OdinHorse = "1.1.0"
OdinPlus-OdinsCraftyBoxes = "1.0.6"
Smoothbrain-Farming = "2.1.6"
Smoothbrain-Foraging = "1.0.0"
Smoothbrain-Lumberjacking = "1.0.3"
Smoothbrain-Mining = "1.1.3"
Smoothbrain-Ranching = "1.1.1"
Smoothbrain-Sailing = "1.1.4"
thedefside-BetterUI_Reforged = "2.4.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./config"
target = "./config"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]
categories = ["modpacks"]
