name: Release

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upload release
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            README.md
            icon.png
            manifest.json
